
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '../components/Button';
import { useAuth } from '../context/AuthContext';
import { storage } from '../services/storage';
import { UserRole, User } from '../types';
import { supabase } from "../supabase";

export const Register: React.FC = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState<UserRole>(UserRole.USER);
  const [error, setError] = useState<string | null>(null);
  const [showSqlGuide, setShowSqlGuide] = useState(false);
  const [loading, setLoading] = useState(false);
  
  const { login } = useAuth();
  const navigate = useNavigate();

  const fullSqlScript = `
-- 1. Table USERS (Liaison avec Auth Supabase)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  role TEXT CHECK (role IN ('user', 'admin')) NOT NULL,
  profile JSONB DEFAULT '{"budget":0,"isSmoker":false,"hasPets":false,"cleanliness":"standard","socialVibe":"balanced","bio":""}'::JSONB
);

-- 2. Table ANNONCES
CREATE TABLE IF NOT EXISTS public.annonces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre TEXT NOT NULL,
  description TEXT,
  auteur_id UUID REFERENCES auth.users NOT NULL,
  auteur_username TEXT,
  date_creation TIMESTAMPTZ DEFAULT NOW(),
  "typeBien" TEXT,
  adresse TEXT,
  ville TEXT,
  surface NUMERIC,
  pieces INT,
  "dateDisponibilite" DATE,
  meuble BOOLEAN DEFAULT FALSE,
  parking BOOLEAN DEFAULT FALSE,
  chauffage TEXT,
  "sourceEnergie" TEXT,
  "dpeConso" NUMERIC,
  "dpeLettre" TEXT,
  "gesEmission" NUMERIC,
  "gesLettre" TEXT,
  "consoFinale" NUMERIC,
  "coutEnergieMin" NUMERIC,
  "coutEnergieMax" NUMERIC,
  "dateIndexationEnergie" DATE,
  photos TEXT[],
  plan TEXT,
  "loyerBase" NUMERIC,
  charges NUMERIC,
  "depotGarantie" NUMERIC,
  "encadrementLoyers" BOOLEAN DEFAULT FALSE,
  "loyerReferenceMajore" NUMERIC
);

-- 3. Table MESSAGES
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender TEXT NOT NULL,
  content TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  read BOOLEAN DEFAULT FALSE
);

-- 4. Table TASKS
CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  "assignedTo" TEXT,
  "isDone" BOOLEAN DEFAULT FALSE,
  "dueDate" TIMESTAMPTZ
);

-- 5. Table EXPENSES
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  "paidBy" TEXT,
  date TIMESTAMPTZ DEFAULT NOW()
);

-- CONFIGURATION SÉCURITÉ (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.annonces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- POLITIQUES (LECTURE PUBLIQUE POUR LE TEST)
CREATE POLICY "Lecture publique users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Lecture publique annonces" ON public.annonces FOR SELECT USING (true);
CREATE POLICY "Lecture publique messages" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Lecture publique tasks" ON public.tasks FOR SELECT USING (true);
CREATE POLICY "Lecture publique expenses" ON public.expenses FOR SELECT USING (true);

-- POLITIQUES (ÉCRITURE AUTHENTIFIÉE)
CREATE POLICY "Modif propre profil" ON public.users FOR ALL USING (auth.uid() = id);
CREATE POLICY "Insert annonces auth" ON public.annonces FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Insert messages auth" ON public.messages FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Insert tasks auth" ON public.tasks FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Insert expenses auth" ON public.expenses FOR INSERT WITH CHECK (auth.role() = 'authenticated');
`.trim();

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setShowSqlGuide(false);

    const cleanEmail = email.trim().toLowerCase();
    
    // Génération automatique du pseudo à partir de l'email
    const generatedUsername = cleanEmail.split('@')[0] || `user_${Math.floor(Math.random() * 1000)}`;

    if (!cleanEmail || !password) {
      setError("Veuillez remplir tous les champs.");
      return;
    }

    setLoading(true);
    try {
        const { data: authData, error: authError } = await supabase.auth.signUp({
          email: cleanEmail,
          password: password,
          options: {
            data: { username: generatedUsername, role: role }
          }
        });

        if (authError) throw authError;
        if (!authData.user) throw new Error("Erreur lors de la création du compte.");

        const newUser: User = {
            id: authData.user.id,
            username: generatedUsername,
            role: role,
            profile: {
                budget: 0,
                isSmoker: false,
                hasPets: false,
                cleanliness: 'standard',
                socialVibe: 'balanced',
                bio: ''
            }
        };

        await storage.addUser(newUser);
        login(newUser);
        alert("Compte créé avec succès !");
        navigate('/');
    } catch (err: any) {
        console.error("Erreur Inscription:", err);
        if (err.message === "DATABASE_NOT_INITIALIZED") {
            setError("Base de données Supabase non initialisée.");
            setShowSqlGuide(true);
        } else if (err.message?.includes("already registered")) {
            setError("Cet email est déjà utilisé.");
        } else {
            setError(err.message || "Une erreur est survenue.");
        }
    } finally {
        setLoading(false);
    }
  };

  return (
    <div className="min-h-[80vh] flex items-center justify-center py-12 px-4 relative">
      <div className="max-w-xl w-full space-y-8 bg-white p-10 rounded-[2.5rem] shadow-2xl border border-slate-100 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-indigo-100 text-indigo-600 mb-6">
            <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
            </svg>
          </div>
          <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">Rejoindre ColocEtudiant</h2>
          <p className="mt-3 text-sm text-slate-500">Inscrivez-vous simplement avec votre email.</p>
        </div>
        
        <form className="mt-8 space-y-6" onSubmit={handleRegister}>
          {error && (
            <div className="bg-red-50 text-red-700 p-6 rounded-3xl text-sm border border-red-100 animate-in fade-in duration-300">
              <div className="flex items-start gap-3">
                <span className="text-xl">🛠️</span>
                <div className="flex-1">
                  <p className="font-bold">{error}</p>
                  {showSqlGuide && (
                    <div className="mt-4">
                      <p className="text-xs text-red-600 mb-3">
                        Copiez ce script dans l'éditeur SQL de <strong>supabase.com</strong> :
                      </p>
                      <div className="relative group">
                        <pre className="bg-slate-900 text-slate-300 p-4 rounded-xl overflow-x-auto text-[10px] font-mono leading-relaxed max-h-48 border border-slate-800">
                            {fullSqlScript}
                        </pre>
                        <button 
                            type="button"
                            onClick={() => {
                                navigator.clipboard.writeText(fullSqlScript);
                                alert("Script SQL copié !");
                            }}
                            className="absolute top-2 right-2 bg-violet-600 text-white text-[10px] px-3 py-1.5 rounded-lg font-bold hover:bg-violet-700"
                        >
                            Copier
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
          
          {!showSqlGuide && (
            <div className="space-y-4">
                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1 ml-1 tracking-wider">Email</label>
                    <input 
                      type="email" 
                      required 
                      className="w-full px-4 py-3 border border-slate-200 rounded-xl bg-slate-50 focus:ring-4 focus:ring-violet-500/10 outline-none transition-all" 
                      value={email} 
                      onChange={(e) => setEmail(e.target.value)} 
                      placeholder="votre@email.com"
                    />
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1 ml-1 tracking-wider">Mot de passe</label>
                    <input 
                      type="password" 
                      required 
                      className="w-full px-4 py-3 border border-slate-200 rounded-xl bg-slate-50 focus:ring-4 focus:ring-violet-500/10 outline-none transition-all" 
                      value={password} 
                      onChange={(e) => setPassword(e.target.value)} 
                    />
                </div>
                <div>
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1 ml-1 tracking-wider">Type de compte</label>
                    <select className="w-full px-4 py-3 border border-slate-200 rounded-xl bg-slate-50 outline-none cursor-pointer" value={role} onChange={(e) => setRole(e.target.value as UserRole)}>
                        <option value={UserRole.USER}>Locataire / Étudiant</option>
                        <option value={UserRole.ADMIN}>Propriétaire / Bailleur</option>
                    </select>
                </div>
                <Button type="submit" className="w-full py-4 mt-4 shadow-xl shadow-violet-500/20" isLoading={loading}>
                  S'inscrire gratuitement
                </Button>
            </div>
          )}
          
          <div className="text-center pt-4">
            <p className="text-sm text-slate-500">
              Déjà inscrit ? <Link to="/login" className="text-violet-600 font-bold hover:underline">Se connecter</Link>
            </p>
          </div>
        </form>
      </div>
    </div>
  );
};